plugins:
  pulselink:
    providers:
      - dzisrc:%ISRC%
      - dzsearch:%QUERY%
      - jssearch:%QUERY%
      - gnsearch:%QUERY%
      - admsearch:%QUERY%
      - bcsearch:%QUERY%
      - scsearch:%QUERY%
    sources:
      spotify: true
      amazonmusic: false
      applemusic: false
      deezer: false
      yandexmusic: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
      audiomack: false
      gaana: false
      shazam: false
      pandora: false
      flowerytts: false
      youtube: false
    lyrics-sources:
      deezer: false
      youtube: false
      yandexmusic: false
      vkmusic: false
      lrcLib: false
    spotify:
      # Optional. Defaults to http://us2.leonodes.xyz:15561
      apiUrl: "http://us2.leonodes.xyz:15561"
      # Optional. Defaults to http://us2.leonodes.xyz:15540/api/token ( For sprec:mix )
      anonymousTokenUrl: "http://us2.leonodes.xyz:15540/api/token"
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6
      resolveArtistsInSearch: true
      localFiles: false
    amazonmusic:
      # Optional. 0-10
      searchLimit: 10
    applemusic:
      countryCode: "US"
      # Optional. Apple Music playback can work without this token.
      mediaAPIToken: "your apple music api token"
    deezer:
      masterDecryptionKey: "your master decryption key"
      arl: "your deezer arl"
      formats: [ "FLAC", "MP3_320", "MP3_256", "MP3_128", "MP3_64", "AAC_64" ]
    yandexmusic:
      accessToken: "your access token"
      playlistLoadLimit: 1
      albumLoadLimit: 1
      artistLoadLimit: 1
    vkmusic:
      userToken: "your user token"
      playlistLoadLimit: 1
      artistLoadLimit: 1
      recommendationsLoadLimit: 10
    tidal:
      countryCode: "US"
      searchLimit: 6
      # Optional. Override only if you want to use your own Tidal token.
      # token: "your tidal token"
      # Optional: direct streaming via hifi-api (third-party)
      hifiApis:
        - "https://hifi-two.spotisaver.net"
      # Optional: order of qualities to try for direct streaming
      hifiQualities: [ "HI_RES_LOSSLESS", "LOSSLESS", "HIGH", "LOW" ]
    ytdlp:
      path: "yt-dlp"
      searchLimit: 10
    audiomack:
      searchLimit: 10
      artistTrackLimit: 25
    gaana:
      # Optional. Defaults to https://gaanapi-wine.vercel.app/
      apiUrl: "https://gaanapi-wine.vercel.app/"
    pandora:
      csrfToken: ""
      authToken: ""
      # Optional. Override only if you want to use your own token provider.
      # remoteTokenUrl: "https://get.1lucas1apk.fun/pandora/gettoken"
    jiosaavn:
      # Built-in defaults are used if you do not override them.
      # decryption:
      #   algorithm: DES
      #   secretKey: "38346591"
      #   transformation: DES/ECB/PKCS5Padding
server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
