name: Publish
permissions:
  contents: read
  packages: write
on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'docker/**'
      - '.github/workflows/docker.yml'
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GRADLE_OPTS: -Dhttps.protocols=TLSv1.2,TLSv1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Publish Packages
        if: github.event_name == 'release'
        run: ./gradlew :plugin:publish --no-daemon -PGITHUB_ACTOR=$GITHUB_ACTOR -PGITHUB_TOKEN=$GITHUB_TOKEN

      - name: Upload plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PulseLink-Plugin.jar
          path: plugin/build/libs/pulselink-plugin-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: PulseLink-Plugin.jar

      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: pulselink-plugin-*.jar
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
